// Copyright (c) 2026 rawdog72 and Prevast Open Server Contributors
// SPDX-License-Identifier: GPL-2.0-only

// tools/accounts/make-ticket-fixtures.ts
// Writes tests/fixtures/accounts/tickets.txt: tickets signed by the web host's
// real signer, each with the result the C++ verifier must give. Consumed by
// `npm run server:selftest` (prevast_server --selftest). Regenerate with
// `npm run accounts:fixtures`; the key is throwaway.
import crypto from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { newNonce, TicketSigner, type TicketClaims } from '../../apps/web/src/accounts/tickets';

const NOW = 1_800_000_000;
// What the web host signs and the game server expects: <listingId>@<host>:<port>.
const SERVER = 'fixture-server@127.0.0.1:7172';
const pem = TicketSigner.generatePem();
const signer = TicketSigner.fromPem(pem);
const stranger = TicketSigner.fromPem(TicketSigner.generatePem());

const claims = (o: Partial<TicketClaims> = {}): TicketClaims => ({
  accountId: 7,
  name: 'Fixture',
  groupId: 2,
  serverId: SERVER,
  expiresAt: NOW + 60,
  nonce: newNonce(),
  ...o,
});
// Signs an arbitrary payload, to prove the verifier rejects well-signed nonsense.
const signRaw = (payload: string): string =>
  `${Buffer.from(payload).toString('base64url')}.${crypto
    .sign('sha256', Buffer.from(payload), { key: crypto.createPrivateKey(pem), dsaEncoding: 'ieee-p1363' })
    .toString('base64url')}`;

const valid = signer.sign(claims());
const [validPayload] = valid.split('.');
const otherSignature = signer.sign(claims({ name: 'Other' })).split('.')[1];

const V6_SERVER = 'fixture-server@[2001:db8::1]:7172';
// [expected result, ticket, server id the verifier expects (default SERVER)]
const cases: [string, string, string?][] = [
  ['Ok', valid],
  ['Replayed', valid],
  ['Ok', signer.sign(claims({ expiresAt: NOW - 29 }))],
  ['Expired', signer.sign(claims({ expiresAt: NOW - 31 }))],
  ['FarFuture', signer.sign(claims({ expiresAt: NOW + 121 }))],
  ['WrongServer', signer.sign(claims({ serverId: 'other-server@127.0.0.1:7172' }))],
  // The right listing id registered from another address: what an operator
  // heartbeating someone else's id would be sent.
  ['WrongServer', signer.sign(claims({ serverId: 'fixture-server@203.0.113.9:7172' }))],
  ['WrongServer', signer.sign(claims({ serverId: 'fixture-server@127.0.0.1:7173' }))],
  ['WrongServer', signer.sign(claims({ serverId: 'fixture-server' }))],
  ['Ok', signer.sign(claims({ serverId: V6_SERVER })), V6_SERVER],
  ['WrongServer', signer.sign(claims({ serverId: 'fixture-server@2001:db8::1:7172' })), V6_SERVER],
  ['BadSignature', `${validPayload}.${otherSignature}`],
  ['BadSignature', stranger.sign(claims())],
  ['Malformed', 'not-a-ticket'],
  ['Malformed', 'a.b.c'],
  ['Malformed', `${'A'.repeat(600)}.${'B'.repeat(86)}`],
  ['Malformed', signRaw(`2|7|Fixture|2|${SERVER}|${NOW + 60}|${newNonce()}`)],
  ['Malformed', signRaw(`1|0|Fixture|2|${SERVER}|${NOW + 60}|${newNonce()}`)],
  ['Malformed', signRaw(`1|7|Fixture|300|${SERVER}|${NOW + 60}|${newNonce()}`)],
  ['Malformed', signRaw(`1|7|Fixture|2|${SERVER}|${NOW + 60}`)],
];

const lines = [
  '# Generated by tools/accounts/make-ticket-fixtures.ts; read by prevast_server --selftest.',
  '# <expected result> <server id> <now, unix seconds> <ticket>, evaluated in order.',
  `key ${signer.publicKeyRaw}`,
  ...cases.map(([expected, ticket, server = SERVER]) => `${expected} ${server} ${NOW} ${ticket}`),
];
mkdirSync('tests/fixtures/accounts', { recursive: true });
writeFileSync('tests/fixtures/accounts/tickets.txt', lines.join('\n') + '\n');
console.log(`Wrote ${cases.length} ticket cases to tests/fixtures/accounts/tickets.txt`);
